// Test service of be-sdk-go internal/rpc: one method per idempotency level and a request with
// batch limits (explicit, default, nested, map). Not part of the SDK's public surface.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: betest/rpc/v1/probe.proto

package probepb

import (
	_ "github.com/brickKit/be-sdk-go/proto/be/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProbeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeRequest) Reset() {
	*x = ProbeRequest{}
	mi := &file_betest_rpc_v1_probe_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeRequest) ProtoMessage() {}

func (x *ProbeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_betest_rpc_v1_probe_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeRequest.ProtoReflect.Descriptor instead.
func (*ProbeRequest) Descriptor() ([]byte, []int) {
	return file_betest_rpc_v1_probe_proto_rawDescGZIP(), []int{0}
}

func (x *ProbeRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ProbeReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Note          string                 `protobuf:"bytes,1,opt,name=note,proto3" json:"note,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProbeReply) Reset() {
	*x = ProbeReply{}
	mi := &file_betest_rpc_v1_probe_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProbeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProbeReply) ProtoMessage() {}

func (x *ProbeReply) ProtoReflect() protoreflect.Message {
	mi := &file_betest_rpc_v1_probe_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProbeReply.ProtoReflect.Descriptor instead.
func (*ProbeReply) Descriptor() ([]byte, []int) {
	return file_betest_rpc_v1_probe_proto_rawDescGZIP(), []int{1}
}

func (x *ProbeReply) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type Filter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuIds        []string               `protobuf:"bytes,1,rep,name=sku_ids,json=skuIds,proto3" json:"sku_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_betest_rpc_v1_probe_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_betest_rpc_v1_probe_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_betest_rpc_v1_probe_proto_rawDescGZIP(), []int{2}
}

func (x *Filter) GetSkuIds() []string {
	if x != nil {
		return x.SkuIds
	}
	return nil
}

type BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	Filter        *Filter                `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Labels        map[string]string      `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_betest_rpc_v1_probe_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_betest_rpc_v1_probe_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_betest_rpc_v1_probe_proto_rawDescGZIP(), []int{3}
}

func (x *BatchRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *BatchRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *BatchRequest) GetFilter() *Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *BatchRequest) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

var File_betest_rpc_v1_probe_proto protoreflect.FileDescriptor

const file_betest_rpc_v1_probe_proto_rawDesc = "" +
	"\n" +
	"\x19betest/rpc/v1/probe.proto\x12\rbetest.rpc.v1\x1a\x12be/v1/limits.proto\"\x1e\n" +
	"\fProbeRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\" \n" +
	"\n" +
	"ProbeReply\x12\x12\n" +
	"\x04note\x18\x01 \x01(\tR\x04note\"'\n" +
	"\x06Filter\x12\x1d\n" +
	"\asku_ids\x18\x01 \x03(\tB\x04\xc8\xf3\x18\x02R\x06skuIds\"\xe5\x01\n" +
	"\fBatchRequest\x12\x16\n" +
	"\x03ids\x18\x01 \x03(\tB\x04\xc8\xf3\x18\x03R\x03ids\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\x12-\n" +
	"\x06filter\x18\x03 \x01(\v2\x15.betest.rpc.v1.FilterR\x06filter\x12?\n" +
	"\x06labels\x18\x04 \x03(\v2'.betest.rpc.v1.BatchRequest.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012\x9d\x02\n" +
	"\x05Probe\x12C\n" +
	"\x04Read\x12\x1b.betest.rpc.v1.ProbeRequest\x1a\x19.betest.rpc.v1.ProbeReply\"\x03\x90\x02\x01\x12D\n" +
	"\x05Touch\x12\x1b.betest.rpc.v1.ProbeRequest\x1a\x19.betest.rpc.v1.ProbeReply\"\x03\x90\x02\x02\x12@\n" +
	"\x06Create\x12\x1b.betest.rpc.v1.ProbeRequest\x1a\x19.betest.rpc.v1.ProbeReply\x12G\n" +
	"\bBatchGet\x12\x1b.betest.rpc.v1.BatchRequest\x1a\x19.betest.rpc.v1.ProbeReply\"\x03\x90\x02\x01b\x06proto3"

var (
	file_betest_rpc_v1_probe_proto_rawDescOnce sync.Once
	file_betest_rpc_v1_probe_proto_rawDescData []byte
)

func file_betest_rpc_v1_probe_proto_rawDescGZIP() []byte {
	file_betest_rpc_v1_probe_proto_rawDescOnce.Do(func() {
		file_betest_rpc_v1_probe_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_betest_rpc_v1_probe_proto_rawDesc), len(file_betest_rpc_v1_probe_proto_rawDesc)))
	})
	return file_betest_rpc_v1_probe_proto_rawDescData
}

var file_betest_rpc_v1_probe_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_betest_rpc_v1_probe_proto_goTypes = []any{
	(*ProbeRequest)(nil), // 0: betest.rpc.v1.ProbeRequest
	(*ProbeReply)(nil),   // 1: betest.rpc.v1.ProbeReply
	(*Filter)(nil),       // 2: betest.rpc.v1.Filter
	(*BatchRequest)(nil), // 3: betest.rpc.v1.BatchRequest
	nil,                  // 4: betest.rpc.v1.BatchRequest.LabelsEntry
}
var file_betest_rpc_v1_probe_proto_depIdxs = []int32{
	2, // 0: betest.rpc.v1.BatchRequest.filter:type_name -> betest.rpc.v1.Filter
	4, // 1: betest.rpc.v1.BatchRequest.labels:type_name -> betest.rpc.v1.BatchRequest.LabelsEntry
	0, // 2: betest.rpc.v1.Probe.Read:input_type -> betest.rpc.v1.ProbeRequest
	0, // 3: betest.rpc.v1.Probe.Touch:input_type -> betest.rpc.v1.ProbeRequest
	0, // 4: betest.rpc.v1.Probe.Create:input_type -> betest.rpc.v1.ProbeRequest
	3, // 5: betest.rpc.v1.Probe.BatchGet:input_type -> betest.rpc.v1.BatchRequest
	1, // 6: betest.rpc.v1.Probe.Read:output_type -> betest.rpc.v1.ProbeReply
	1, // 7: betest.rpc.v1.Probe.Touch:output_type -> betest.rpc.v1.ProbeReply
	1, // 8: betest.rpc.v1.Probe.Create:output_type -> betest.rpc.v1.ProbeReply
	1, // 9: betest.rpc.v1.Probe.BatchGet:output_type -> betest.rpc.v1.ProbeReply
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_betest_rpc_v1_probe_proto_init() }
func file_betest_rpc_v1_probe_proto_init() {
	if File_betest_rpc_v1_probe_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_betest_rpc_v1_probe_proto_rawDesc), len(file_betest_rpc_v1_probe_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_betest_rpc_v1_probe_proto_goTypes,
		DependencyIndexes: file_betest_rpc_v1_probe_proto_depIdxs,
		MessageInfos:      file_betest_rpc_v1_probe_proto_msgTypes,
	}.Build()
	File_betest_rpc_v1_probe_proto = out.File
	file_betest_rpc_v1_probe_proto_goTypes = nil
	file_betest_rpc_v1_probe_proto_depIdxs = nil
}
