// be-protocol 1.0: field options of the component protocol (P7.10).
//
// Import this file and annotate a repeated field of IDs with its batch limit:
//   repeated string ids = 1 [(be.v1.max_items) = 100];
// Without the option the limit is 500. A request above the limit answers INVALID_ARGUMENT with
// ErrorInfo{reason: BATCH_TOO_LARGE, domain: be, metadata: {field, max, got}} plus BadRequest.
//
// Short names: some generators (ts-proto among them) expose a custom option by its short name,
// without its package. Every option of the be.* packages therefore has a short name unique across
// every option a component's protos can see: `max_items` is taken, and a later option never reuses
// the short name of any option, ours or another package's (P7.10).
//
// No go_package is set: this repository ships no generated code. Every official SDK ships the
// generated code of this file (Go: the SDK's package, mapped with M be/v1/limits.proto=<package>;
// Python: an importable be.v1.limits_pb2; TypeScript: the SDK's module), so a component's
// generated code links to one copy.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: be/v1/limits.proto

package bev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var file_be_v1_limits_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*int32)(nil),
		Field:         51001,
		Name:          "be.v1.max_items",
		Tag:           "varint,51001,opt,name=max_items",
		Filename:      "be/v1/limits.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// Maximum number of items a repeated field accepts in one request.
	//
	// optional int32 max_items = 51001;
	E_MaxItems = &file_be_v1_limits_proto_extTypes[0]
)

var File_be_v1_limits_proto protoreflect.FileDescriptor

const file_be_v1_limits_proto_rawDesc = "" +
	"\n" +
	"\x12be/v1/limits.proto\x12\x05be.v1\x1a google/protobuf/descriptor.proto:<\n" +
	"\tmax_items\x12\x1d.google.protobuf.FieldOptions\x18\xb9\x8e\x03 \x01(\x05R\bmaxItemsb\x06proto3"

var file_be_v1_limits_proto_goTypes = []any{
	(*descriptorpb.FieldOptions)(nil), // 0: google.protobuf.FieldOptions
}
var file_be_v1_limits_proto_depIdxs = []int32{
	0, // 0: be.v1.max_items:extendee -> google.protobuf.FieldOptions
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_be_v1_limits_proto_init() }
func file_be_v1_limits_proto_init() {
	if File_be_v1_limits_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_be_v1_limits_proto_rawDesc), len(file_be_v1_limits_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_be_v1_limits_proto_goTypes,
		DependencyIndexes: file_be_v1_limits_proto_depIdxs,
		ExtensionInfos:    file_be_v1_limits_proto_extTypes,
	}.Build()
	File_be_v1_limits_proto = out.File
	file_be_v1_limits_proto_goTypes = nil
	file_be_v1_limits_proto_depIdxs = nil
}
